#!/usr/bin/env bash

## Install ansible
#sudo apt-add-repository -y ppa:ansible/ansible
#sudo apt-get update -y
#sudo apt-get install -y curl git software-properties-common ansible


sudo apt update
sudo apt install python3-pip


pip3 install ansible
