# vim: set filetype=yaml.ansible :/
- name: Local
  hosts: localhost
  vars:
    bin: "{{ lookup('env', 'HOME') }}/bin"
#    source_key: "./.ssh/id_rsa"
#    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
#    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - name: Core
      ansible.builtin.import_tasks: tasks/core.yml
    - name: Git
      ansible.builtin.import_tasks: tasks/git.yml
    - name: Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
    - name: Rust
      ansible.builtin.import_tasks: tasks/rust.yml
    - name: Qemu
      ansible.builtin.import_tasks: tasks/qemu.yml
    - name: Brave
      ansible.builtin.import_tasks: tasks/brave.yml
    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml

    # - include: tasks/ssh.yml
    # - include: tasks/node-setup.yml
    # - include: tasks/npm-packages.yml
    # - include: tasks/zsh-setup.yml
    # - include: tasks/slack-setup.yml
    # - include: tasks/personal-projects.yml
    # - include: tasks/debugger.yml
    # - include: tasks/productivity-tools.yml
    # - include: tasks/lsp.yml
