# vim: set filetype=yaml.ansible :/
- name: Local
  hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    bin: "{{ home }}/bin"
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    ########
    # Core #
    - name: Core
      block:
        - name: Install basic Utils (curl, git, unzip, fzf)
          become: true
          ansible.builtin.apt:
            name:
              - curl
              - git
              - unzip
              - fzf
          tags:
            - dotfiles
            - neovim
            - rust
            - brave

        - name: Install build utils (checkinstall)
          become: true
          ansible.builtin.apt:
            name: ["checkinstall"]
          tags:
            - neovim

        # - name: Install Doas
        #   ansible.builtin.import_tasks: tasks/doas.yml
        #   tags:
        #     - doas
        #     - bash
        #     - dotfiles

        - name: Install Openssl (dev)
          become: true
          ansible.builtin.apt:
            name:
              - pkg-config
              - libssl-dev

    #############
    # Languages #
    - name: Rust
      tags:
        - rust
        - terminal
      block:
        - name: Rust Environment
          ansible.builtin.import_tasks: tasks/rust-env.yml
          tags: dotfiles

        - name: Rust-lang
          ansible.builtin.import_tasks: tasks/rust.yml

    - name: Node.js
      ansible.builtin.import_tasks: tasks/node.yml
      tags:
        - node
        - neovim

    ###########
    # Configs #
    - name: Git Config
      ansible.builtin.import_tasks: tasks/git.yml
      tags: git

    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - neovim
        - bash
        - terminal
        - tmux
        - awesome

    ################
    # Applications #
    - name: Rust tools
      ansible.builtin.import_tasks: tasks/rust-tools.yml
      tags:
        - rust
        - terminal

    - name: Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
      tags: neovim

    - name: Terminal
      ansible.builtin.import_tasks: tasks/terminal.yml
      tags: terminal

    - name: Tmux
      ansible.builtin.import_tasks: tasks/tmux.yml
      tags: tmux

    - name: AwesomeWM
      ansible.builtin.import_tasks: tasks/awesome.yml
      tags: awesome

    - name: Qemu
      ansible.builtin.import_tasks: tasks/qemu.yml
      tags: qemu

    # - name: Brave
    #   ansible.builtin.import_tasks: tasks/brave.yml
    #   tags: brave
