# vim: set filetype=yaml.ansible :/
- name: Installing Awesome build dependencies
  become: true
  ansible.builtin.apt:
    name: awesome
    state: build-dep

- name: Cloning Awesome
  ansible.builtin.git:
    repo: "https://github.com/awesomeWM/awesome"
    dest: "{{ bin }}/awesome"
    update: true
    force: true
  register: git_result

- name: Neovim Build Process
  when: git_result.changed
  block:
    - name: Removing old build directory
      ansible.builtin.file:
        path: "{{ bin }}/awesome/build"
        state: absent

    - name: Building .deb package
      ansible.builtin.command: make package
      args:
        chdir: "{{ bin }}/awesome"

    - name: Searching .deb package
      ansible.builtin.find:
        paths: "{{ bin }}/awesome/build"
        patterns: "*.deb"
      register: deb_packages

    - name: Installing .deb package
      become: true
      ansible.builtin.apt:
        deb: "{{ deb_packages.files[0].path }}"
      # loop: "{{ deb_packages.files | flatten(levels=1) }}"
      # loop_control:
      #   label: "{{ item.path }}"
