# vim: set filetype=yaml.ansible :/
- name: Installing Doas
  become: true
  ansible.builtin.apt:
    name: doas

- name: Searching /etc/doas.conf
  become: true
  ansible.builtin.stat:
    path: /etc/doas.conf
  register: conf_stat

- name: Creating /etc/doas.conf
  become: true
  ansible.builtin.shell: echo "permit :sudo" | tee /etc/doas.conf # "permit :wheel"
  when: not conf_stat.stat.exists
