# vim: set filetype=yaml.ansible :/
- name: Linking .cargo and .rustup
  vars:
    src: "/usr/share/rust/{{ item }}"
    dest: "{{ home }}/{{ item }}"
  ansible.builtin.file:
    src: "{{ src }}"
    dest: "{{ dest }}"
    state: link
  loop:
    - .cargo
    - .rustup
  loop_control:
    label: "{{ dest }} -> {{ src }}"

- name: Installing or Updating Rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly --no-modify-path -y
