# vim: set filetype=yaml.ansible :/
- name: Installing or Updating Rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly --no-modify-path -y

- name: Install Sccache
  ansible.builtin.command: cargo install sccache
