# vim: set filetype=yaml.ansible :/
- name: Installing Starship Shell
  ansible.builtin.command: cargo install starship --locked

- name: Installing Alacritty Terminal
  ansible.builtin.command: cargo install alacritty
  environment:
    PKG_CONFIG_PATH: "/usr/lib/x86_64-linux-gnu/pkgconfig"
