# vim: set filetype=yaml.ansible :/
- name: Test 1
  ansible.builtin.debug:
    msg: "{{ test }}"

- name: Test
  vars:
    dotfiles: "{{ lookup('env', 'HOME') }}/.dotfiles"
  block:
    - name: Read .config dotfiles
      ansible.builtin.find:
        paths: "{{ dotfiles }}/.config"
        file_type: "any"
      register: dotfiles_list

    - name: Read Targets
      vars:
        is_valid_line: "{{ (item | trim)[:1] != '#' }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item.split(';')[1] | trim }}"
        src: "{{ dotfiles }}/{{ item.split(';')[0] | trim }}"
      ansible.builtin.file:
        dest: "{{ dest }}"
        src: "{{ src }}"
        state: link
        force: true # replace existing files!
      loop: "{{ lookup('ansible.builtin.file', '{{ dotfiles }}/TARGETS').splitlines() }}"
      when: is_valid_line
      loop_control:
        label: "{{ dest }} -> {{ src }}"
